/**
 * Data layer for the Aggregate Stats views — STATIC build.
 *
 * Loads two baked JSON files once (public/data, regenerated by server scripts/bake-static.ts)
 * and serves everything client-side, so the deployed site needs no backend or database.
 *
 * Backend honesty: only top-division LEAGUE titles exist (no cup/other trophies), so `cup`/`oth`
 * are 0 and a manager's cabinet holds only championships. Data is a frozen snapshot — re-bake +
 * re-deploy to refresh.
 */

import { leagueFlagUrl } from './flags.js';

export interface Country {
  code: string;
  name: string;
}

export interface Manager {
  userId: number;
  login: string;
  c: string;
  team: string;
  lg: number;
  main: number; // main national cup wins (attributed)
  sec: number; // secondary/consolation cup wins (attributed)
  hm: number; // Hattrick Masters wins (the global champions-of-champions cup)
  sn: number; // Seasonal Cups wins (global recurring tournaments, e.g. Supporter Week Trophy)
  wc: number; // World Cup wins as coach (senior + youth combined — see sync/worldCup.ts)
  oth: number;
  lgLast: number; // reigning league titles (current champion of that league)
  mainLast: number; // reigning main-cup titles (current holder of that cup)
  secLast: number; // reigning secondary/consolation-cup titles
  hmLast: number; // reigning Hattrick Masters title (holder of the most recent edition)
  snLast: number; // reigning Seasonal Cups titles (holder of the most recent edition)
  wcLast: number; // reigning World Cup title(s) (per bracket — senior and youth reign separately)
}

export interface TrophyItem {
  main: string;
  sub: string;
  season: string;
  last?: boolean; // the reigning/most-recent trophy of its competition
  flag?: string | null; // country-flag URL (by leagueId); null for the country-less Masters/World Cup
}

export interface TrophyCabinet {
  champ: TrophyItem[];
  main: TrophyItem[];
  sec: TrophyItem[];
  other: TrophyItem[]; // the Hattrick Masters
  seasonal: TrophyItem[]; // Seasonal Cups (Supporter Week Trophy)
  worldCup: TrophyItem[]; // World Cup wins as coach (senior + youth)
}

export interface Winner {
  season: number;
  club: string;
  manager: string;
  /** Manager's nationality (country name, matches NATIONALITY_ISO in flags.ts), joined by login name
   *  from managers.json — best-effort like the rest of the retro views' name-based joins. */
  nationality?: string;
  /** Real Hattrick ids, present only where the sync pipeline actually resolved them — link out to
   *  hattrick.org when set, render as plain text otherwise. Coverage varies a lot by category:
   *  league/national-cup champions rarely have a stored teamId (the manager is attributed directly,
   *  without ever resolving a team), while Masters and Seasonal Cups usually do (see bake.ts). */
  teamId?: number;
  userId?: number;
}

export type CupWinner = Winner;

export interface CupRoll {
  cupId: number;
  cupName: string;
  isMain: boolean;
  cupLevel: number;
  cupLevelIndex: number;
  winners: CupWinner[];
}

export interface CupCountry {
  leagueId: number;
  country: string;
  cups: CupRoll[];
}

interface RawCup {
  country: string;
  leagueId?: number;
  season: number;
  club: string;
  cup: string;
  last?: boolean;
}
interface RawManager {
  userId: number;
  userName: string;
  nationality: string;
  lg: number;
  main: number;
  sec: number;
  hm?: number;
  sn?: number;
  wc?: number;
  lgLast?: number;
  mainLast?: number;
  secLast?: number;
  hmLast?: number;
  snLast?: number;
  wcLast?: number;
  titles: Array<{ country: string; leagueId?: number; season: number; club: string; last?: boolean }>;
  cupsMain: RawCup[];
  cupsSec: RawCup[];
  masters?: RawCup[];
  seasonal?: RawCup[];
  worldCup?: RawCup[];
}
interface RawLeague {
  leagueId: number;
  country: string;
  champions: Array<{ season: number; club: string; manager: string }>;
}

let bundle: Promise<{ managers: RawManager[]; leagues: RawLeague[] }> | null = null;
function load() {
  if (!bundle) {
    bundle = Promise.all([
      fetch('/data/managers.json').then((r) => r.json() as Promise<RawManager[]>),
      fetch('/data/leagues.json').then((r) => r.json() as Promise<RawLeague[]>),
    ]).then(([managers, leagues]) => ({ managers, leagues }));
  }
  return bundle;
}

// Cups load lazily on their own — the Cup winners view is the only consumer, and cups.json is
// large, so we don't pull it into the initial bundle. Missing file (older bake) → empty list.
let cupsBundle: Promise<CupCountry[]> | null = null;
function loadCups() {
  if (!cupsBundle) {
    cupsBundle = fetch('/data/cups.json')
      .then((r) => (r.ok ? (r.json() as Promise<CupCountry[]>) : []))
      .catch(() => []);
  }
  return cupsBundle;
}

export async function getCupCountries(): Promise<Country[]> {
  const cups = await loadCups();
  return cups.map((c) => ({ code: String(c.leagueId), name: c.country }));
}

/** International cupId of the Supporter Week Trophy — mirrors server/src/sync/seasonal.ts. Every
 *  other entry in seasonal.json is a "Heroes/Titans of YYYY Trophy" (Generation) cohort. */
export const SUPPORTER_WEEK_CUP_ID = 2108472;

interface RawSeasonalCup {
  cupId: number;
  cupName: string;
  winners: Array<{ season: number; club: string; manager: string }>;
}
let seasonalBundle: Promise<RawSeasonalCup[]> | null = null;
function loadSeasonal() {
  if (!seasonalBundle) {
    seasonalBundle = fetch('/data/seasonal.json')
      .then((r) => (r.ok ? (r.json() as Promise<RawSeasonalCup[]>) : []))
      .catch(() => []);
  }
  return seasonalBundle;
}

export interface SeasonalCupRoll {
  cupId: number;
  cupName: string;
  isGeneration: boolean; // false for Supporter Week Trophy, true for every "Heroes/Titans of YYYY" cohort
  winners: Winner[];
}

/** Every Seasonal Cup's roll of honour — Supporter Week Trophy plus all "Heroes/Titans of YYYY"
 *  (Generation) cohorts, each its own perpetual tournament (see sync/seasonal.ts). */
export async function getSeasonalCups(): Promise<SeasonalCupRoll[]> {
  const [raw, { managers }] = await Promise.all([loadSeasonal(), load()]);
  const natByLogin = new Map(managers.map((m) => [m.userName, m.nationality]));
  return raw.map((c) => ({
    cupId: c.cupId,
    cupName: c.cupName,
    isGeneration: c.cupId !== SUPPORTER_WEEK_CUP_ID,
    winners: c.winners.map((w) => ({ ...w, nationality: natByLogin.get(w.manager) })),
  }));
}

let mastersBundle: Promise<Array<{ season: number; club: string; manager: string }>> | null = null;
function loadMasters() {
  if (!mastersBundle) {
    mastersBundle = fetch('/data/masters.json')
      .then((r) => (r.ok ? (r.json() as Promise<Array<{ season: number; club: string; manager: string }>>) : []))
      .catch(() => []);
  }
  return mastersBundle;
}

/** The Hattrick Masters roll of honour — international, no country (see sync/masters.ts). */
export async function getMastersWinners(): Promise<Winner[]> {
  const [raw, { managers }] = await Promise.all([loadMasters(), load()]);
  const natByLogin = new Map(managers.map((m) => [m.userName, m.nationality]));
  return raw.map((w) => ({ ...w, nationality: natByLogin.get(w.manager) }));
}

export async function getCups(leagueId: string): Promise<CupRoll[]> {
  const [cups, { managers }] = await Promise.all([loadCups(), load()]);
  const country = cups.find((c) => String(c.leagueId) === leagueId);
  if (!country) return [];
  const natByLogin = new Map(managers.map((m) => [m.userName, m.nationality]));
  return country.cups.map((c) => ({ ...c, winners: c.winners.map((w) => ({ ...w, nationality: natByLogin.get(w.manager) })) }));
}

export async function getNationalities(): Promise<Country[]> {
  const { managers } = await load();
  const counts = new Map<string, number>();
  for (const m of managers) counts.set(m.nationality, (counts.get(m.nationality) ?? 0) + 1);
  return [...counts.entries()]
    .filter(([n]) => n && n !== 'Unknown')
    .sort((a, b) => b[1] - a[1])
    .map(([nationality, n]) => ({ code: nationality, name: `${nationality} (${n})` }));
}

export async function getLeagues(): Promise<Country[]> {
  const { leagues } = await load();
  return leagues.map((l) => ({ code: String(l.leagueId), name: l.country }));
}

/**
 * Fallback for bakes that predate the per-item `last` flag: each country's latest league season.
 * Each country runs its own season clock, so the reigning season is per-country. Lets league
 * reigning resolve client-side before a re-bake; baked `last` flags take precedence when present.
 */
function latestLeagueSeasonByCountry(leagues: RawLeague[]): Map<string, number> {
  const latest = new Map<string, number>();
  for (const l of leagues)
    for (const c of l.champions) {
      const cur = latest.get(l.country);
      if (cur === undefined || c.season > cur) latest.set(l.country, c.season);
    }
  return latest;
}

export async function getManagers(nationality?: string): Promise<Manager[]> {
  const { managers, leagues } = await load();
  const latestByCountry = latestLeagueSeasonByCountry(leagues);

  return managers
    .filter((m) => !nationality || nationality === 'ALL' || m.nationality === nationality)
    .map((m) => {
      const titles = m.titles ?? [];
      const lgLast =
        m.lgLast ??
        (titles.some((t) => t.last !== undefined)
          ? titles.filter((t) => t.last).length
          : titles.filter((t) => latestByCountry.get(t.country) === t.season).length);
      return {
        userId: m.userId,
        login: m.userName,
        c: m.nationality,
        team: '',
        lg: m.lg,
        main: m.main ?? 0,
        sec: m.sec ?? 0,
        hm: m.hm ?? 0,
        sn: m.sn ?? 0,
        wc: m.wc ?? 0,
        oth: 0,
        lgLast,
        mainLast: m.mainLast ?? (m.cupsMain ?? []).filter((c) => c.last).length,
        secLast: m.secLast ?? (m.cupsSec ?? []).filter((c) => c.last).length,
        hmLast: m.hmLast ?? (m.masters ?? []).filter((c) => c.last).length,
        snLast: m.snLast ?? (m.seasonal ?? []).filter((c) => c.last).length,
        wcLast: m.wcLast ?? (m.worldCup ?? []).filter((c) => c.last).length,
      };
    });
}

export async function getCabinet(userId: number): Promise<TrophyCabinet> {
  const { managers, leagues } = await load();
  const m = managers.find((x) => x.userId === userId);
  // Mirror getManagers' league fallback so an expanded cabinet stays consistent with the chart
  // under "Reigning only" even before a re-bake (cups need the bake — no `last`, no fallback).
  const latestByCountry = latestLeagueSeasonByCountry(leagues);
  const champ = (m?.titles ?? []).map((t) => ({
    main: `${t.country} champions`,
    sub: t.club,
    season: 'S' + t.season,
    last: t.last ?? latestByCountry.get(t.country) === t.season,
    flag: leagueFlagUrl(t.leagueId),
  }));
  const cupItems = (cups?: RawCup[]) => (cups ?? []).map((t) => ({ main: t.cup, sub: t.club, season: 'S' + t.season, last: t.last, flag: leagueFlagUrl(t.leagueId) }));
  // `other` carries the Hattrick Masters, `seasonal` the Seasonal Cups, `worldCup` the World Cup
  // (senior + youth) — each its own category (see bake.ts / sync/masters.ts / sync/seasonal.ts /
  // sync/worldCup.ts). All three are country-less, so no flag.
  return {
    champ, main: cupItems(m?.cupsMain), sec: cupItems(m?.cupsSec),
    other: cupItems(m?.masters), seasonal: cupItems(m?.seasonal), worldCup: cupItems(m?.worldCup),
  };
}

export async function getWinners(leagueId: string): Promise<Winner[]> {
  const { leagues, managers } = await load();
  const l = leagues.find((x) => String(x.leagueId) === leagueId);
  if (!l) return [];
  const natByLogin = new Map(managers.map((m) => [m.userName, m.nationality]));
  return l.champions.map((c) => ({ ...c, nationality: natByLogin.get(c.manager) }));
}

/**
 * World Cup (senior + youth) — the champion is a NATION, not a manager/club, so it's a completely
 * separate shape from Winner. No CHPP path exists for national-team competitions (cupmatches
 * returns nothing); the full roll of honour was scraped once from World/WorldCup/History.aspx
 * (see server/sync/worldCup.ts). The youth bracket was "U20" through edition 31, "U21" after.
 */
export interface WorldCupEdition {
  edition: number;
  ageGroup?: string;
  host: string;
  finished: string | null; // "DD.MM.YYYY", null while ongoing
  champion: string | null; // nation name, null while ongoing
  runnerUp: string | null;
  thirdFourth: string[];
  /** The manager coaching the champion nation when the edition finished (cross-referenced from
   *  NTFormerCoaches.aspx — see sync/worldCup.ts). Undefined when unattributed: "Retired user"
   *  tenure, no tenure recorded that far back, or the nation's team id never resolved. */
  coachUserId?: number;
  coach?: string;
  coachNationality?: string;
}
export interface WorldCupHistory {
  senior: WorldCupEdition[];
  youth: WorldCupEdition[];
}

let worldCupBundle: Promise<WorldCupHistory> | null = null;
export async function getWorldCup(): Promise<WorldCupHistory> {
  if (!worldCupBundle) {
    worldCupBundle = fetch('/data/worldcup.json')
      .then((r) => (r.ok ? (r.json() as Promise<WorldCupHistory>) : { senior: [], youth: [] }))
      .catch(() => ({ senior: [], youth: [] }));
  }
  return worldCupBundle;
}
