/**
 * Data layer for the Aggregate Stats views — STATIC build.
 *
 * Loads two baked JSON files once (public/data, regenerated by server scripts/bake-static.ts)
 * and serves everything client-side, so the deployed site needs no backend or database.
 *
 * Backend honesty: only top-division LEAGUE titles exist (no cup/other trophies), so `cup`/`oth`
 * are 0 and a manager's cabinet holds only championships. Data is a frozen snapshot — re-bake +
 * re-deploy to refresh.
 */

import { LEAGUE_ISO, NATIONALITY_ISO, leagueFlagUrl, nationFlagUrl } from './flags.js';

export interface Country {
  code: string;
  name: string;
}

export interface Manager {
  userId: number;
  login: string;
  c: string;
  team: string;
  lg: number;
  main: number; // main national cup wins (attributed)
  sec: number; // secondary/consolation cup wins (attributed)
  hm: number; // Hattrick Masters wins (the global champions-of-champions cup)
  sn: number; // Seasonal Cups wins (global recurring tournaments, e.g. Supporter Week Trophy)
  /** "National trophies": titles won as a NATIONAL COACH. The World Cup (senior + youth) today —
   *  the regional and alternate cups will land in this same bucket (see sync/worldCup.ts). The
   *  `wc`/`worldCup` names are the baked wire format and stay as they are. */
  wc: number;
  /** Podium places short of the title, in those same national competitions. Never folded into `wc`:
   *  a runner-up is not a trophy, so titles-only totals stay exactly what they always were. */
  wcSilver: number;
  wcBronze: number;
  oth: number;
  lgLast: number; // reigning league titles (current champion of that league)
  mainLast: number; // reigning main-cup titles (current holder of that cup)
  secLast: number; // reigning secondary/consolation-cup titles
  hmLast: number; // reigning Hattrick Masters title (holder of the most recent edition)
  snLast: number; // reigning Seasonal Cups titles (holder of the most recent edition)
  wcLast: number; // reigning World Cup title(s) (per bracket — senior and youth reign separately)
}

export interface TrophyItem {
  main: string;
  sub: string;
  season: string;
  /** The winning club's real Hattrick id, when the pipeline resolved one — links `sub` out to
   *  hattrick.org. Absent for reconstructed placeholders and for the World Cup, whose "club" is a
   *  nation with no team id at all. */
  teamId?: number;
  last?: boolean; // the reigning/most-recent trophy of its competition
  flag?: string | null; // country-flag URL (by leagueId); null for the country-less Masters/World Cup
}

export interface TrophyCabinet {
  champ: TrophyItem[];
  main: TrophyItem[];
  sec: TrophyItem[];
  other: TrophyItem[]; // the Hattrick Masters
  seasonal: TrophyItem[]; // Seasonal Cups (Supporter Week Trophy)
  worldCup: TrophyItem[]; // "National trophies" — titles won as a national coach (World Cup today)
  /** Podium places short of the title, in those same national competitions. Kept apart from
   *  `worldCup` so a medal is never mistaken for a trophy — the UI shows them as their own groups. */
  silver: TrophyItem[];
  bronze: TrophyItem[];
}

export interface Winner {
  season: number;
  club: string;
  manager: string;
  /** Manager's nationality (country name, matches NATIONALITY_ISO in flags.ts), joined by login name
   *  from managers.json — best-effort like the rest of the retro views' name-based joins. */
  nationality?: string;
  /** Real Hattrick ids, present only where the sync pipeline actually resolved them — link out to
   *  hattrick.org when set, render as plain text otherwise. Coverage varies a lot by category:
   *  league/national-cup champions rarely have a stored teamId (the manager is attributed directly,
   *  without ever resolving a team), while Masters and Seasonal Cups usually do (see bake.ts). */
  teamId?: number;
  userId?: number;
}

export type CupWinner = Winner;

export interface CupRoll {
  cupId: number;
  cupName: string;
  isMain: boolean;
  cupLevel: number;
  cupLevelIndex: number;
  winners: CupWinner[];
}

export interface CupCountry {
  leagueId: number;
  country: string;
  cups: CupRoll[];
}

interface RawCup {
  country: string;
  leagueId?: number;
  season: number;
  club: string;
  teamId?: number;
  cup: string;
  last?: boolean;
  /** How many of this competition's own instalments back the trophy is: 0 = current holder.
   *  Baked, not derived — see `SeasonWindow`. */
  ago?: number;
}
interface RawManager {
  userId: number;
  userName: string;
  nationality: string;
  lg: number;
  main: number;
  sec: number;
  hm?: number;
  sn?: number;
  wc?: number;
  wcSilver?: number;
  wcBronze?: number;
  lgLast?: number;
  mainLast?: number;
  secLast?: number;
  hmLast?: number;
  snLast?: number;
  wcLast?: number;
  titles: Array<{ country: string; leagueId?: number; season: number; club: string; teamId?: number; last?: boolean; ago?: number }>;
  cupsMain: RawCup[];
  cupsSec: RawCup[];
  masters?: RawCup[];
  seasonal?: RawCup[];
  worldCup?: RawCup[];
  /** One entry per podium place short of the title: place 2 = silver, 3 = bronze. `ago` follows
   *  the same rule as RawCup. */
  medals?: Array<{ cup: string; season: number; nation: string; leagueId?: number; place: number; ago?: number }>;
}
interface RawLeague {
  leagueId: number;
  country: string;
  champions: Array<{ season: number; club: string; manager: string }>;
}

let bundle: Promise<{ managers: RawManager[]; leagues: RawLeague[] }> | null = null;
function load() {
  if (!bundle) {
    bundle = Promise.all([
      fetch('/data/managers.json').then((r) => r.json() as Promise<RawManager[]>),
      fetch('/data/leagues.json').then((r) => r.json() as Promise<RawLeague[]>),
    ]).then(([managers, leagues]) => ({ managers, leagues }));
  }
  return bundle;
}

// Cups load lazily on their own — the Cup winners view is the only consumer, and cups.json is
// large, so we don't pull it into the initial bundle. Missing file (older bake) → empty list.
let cupsBundle: Promise<CupCountry[]> | null = null;
function loadCups() {
  if (!cupsBundle) {
    cupsBundle = fetch('/data/cups.json')
      .then((r) => (r.ok ? (r.json() as Promise<CupCountry[]>) : []))
      .catch(() => []);
  }
  return cupsBundle;
}

export async function getCupCountries(): Promise<Country[]> {
  const cups = await loadCups();
  return cups.map((c) => ({ code: String(c.leagueId), name: c.country }));
}

/** International cupId of the Supporter Week Trophy — mirrors server/src/sync/seasonal.ts. Every
 *  other entry in seasonal.json is a "Heroes/Titans of YYYY Trophy" (Generation) cohort. */
export const SUPPORTER_WEEK_CUP_ID = 2108472;

interface RawSeasonalCup {
  cupId: number;
  cupName: string;
  winners: Array<{ season: number; club: string; manager: string }>;
}
let seasonalBundle: Promise<RawSeasonalCup[]> | null = null;
function loadSeasonal() {
  if (!seasonalBundle) {
    seasonalBundle = fetch('/data/seasonal.json')
      .then((r) => (r.ok ? (r.json() as Promise<RawSeasonalCup[]>) : []))
      .catch(() => []);
  }
  return seasonalBundle;
}

export interface SeasonalCupRoll {
  cupId: number;
  cupName: string;
  isGeneration: boolean; // false for Supporter Week Trophy, true for every "Heroes/Titans of YYYY" cohort
  winners: Winner[];
}

/** Every Seasonal Cup's roll of honour — Supporter Week Trophy plus all "Heroes/Titans of YYYY"
 *  (Generation) cohorts, each its own perpetual tournament (see sync/seasonal.ts). */
export async function getSeasonalCups(): Promise<SeasonalCupRoll[]> {
  const [raw, { managers }] = await Promise.all([loadSeasonal(), load()]);
  const natByLogin = new Map(managers.map((m) => [m.userName, m.nationality]));
  return raw.map((c) => ({
    cupId: c.cupId,
    cupName: c.cupName,
    isGeneration: c.cupId !== SUPPORTER_WEEK_CUP_ID,
    winners: c.winners.map((w) => ({ ...w, nationality: natByLogin.get(w.manager) })),
  }));
}

let mastersBundle: Promise<Array<{ season: number; club: string; manager: string }>> | null = null;
function loadMasters() {
  if (!mastersBundle) {
    mastersBundle = fetch('/data/masters.json')
      .then((r) => (r.ok ? (r.json() as Promise<Array<{ season: number; club: string; manager: string }>>) : []))
      .catch(() => []);
  }
  return mastersBundle;
}

/** The Hattrick Masters roll of honour — international, no country (see sync/masters.ts). */
export async function getMastersWinners(): Promise<Winner[]> {
  const [raw, { managers }] = await Promise.all([loadMasters(), load()]);
  const natByLogin = new Map(managers.map((m) => [m.userName, m.nationality]));
  return raw.map((w) => ({ ...w, nationality: natByLogin.get(w.manager) }));
}

export async function getCups(leagueId: string): Promise<CupRoll[]> {
  const [cups, { managers }] = await Promise.all([loadCups(), load()]);
  const country = cups.find((c) => String(c.leagueId) === leagueId);
  if (!country) return [];
  const natByLogin = new Map(managers.map((m) => [m.userName, m.nationality]));
  return country.cups.map((c) => ({ ...c, winners: c.winners.map((w) => ({ ...w, nationality: natByLogin.get(w.manager) })) }));
}

export async function getNationalities(): Promise<Country[]> {
  const { managers } = await load();
  const counts = new Map<string, number>();
  for (const m of managers) counts.set(m.nationality, (counts.get(m.nationality) ?? 0) + 1);
  return [...counts.entries()]
    .filter(([n]) => n && n !== 'Unknown')
    .sort((a, b) => b[1] - a[1])
    .map(([nationality, n]) => ({ code: nationality, name: `${nationality} (${n})` }));
}

export async function getLeagues(): Promise<Country[]> {
  const { leagues } = await load();
  return leagues.map((l) => ({ code: String(l.leagueId), name: l.country }));
}

/**
 * Fallback for bakes that predate the per-item `last` flag: each country's latest league season.
 * Each country runs its own season clock, so the reigning season is per-country. Lets league
 * reigning resolve client-side before a re-bake; baked `last` flags take precedence when present.
 */
function latestLeagueSeasonByCountry(leagues: RawLeague[]): Map<string, number> {
  const latest = new Map<string, number>();
  for (const l of leagues)
    for (const c of l.champions) {
      const cur = latest.get(l.country);
      if (cur === undefined || c.season > cur) latest.set(l.country, c.season);
    }
  return latest;
}

/**
 * Trophies within a recency window, and the reason this is one field comparison.
 *
 * Hattrick numbers league seasons PER LEAGUE from that league's founding: Italy and England are on
 * season 94 while Rwanda is on 6 and Gibraltar on 2. There is no global "season 90", so a window
 * has to be measured from each competition's own latest instalment. The bake does exactly that and
 * stores the distance as `ago` — 0 for the current holder, 1 for the one before it (see
 * server/sync/bake.ts `agoOf`).
 *
 * Deliberately NOT re-derived here. The bake anchors on every champion on record, including ones
 * never attributed to a manager, while managers.json holds only the attributed ones — so deriving
 * the anchor from this file lands early wherever a competition's newest winner is unknown, and an
 * older trophy counts as current. That cost 7 cups their correct "Last season" count before `ago`
 * existed. Taking it from the bake makes a window of 1 and "Reigning only" agree by construction.
 */
export type SeasonWindow = 1 | 5 | 10 | 20;

/** The `window` most recent instalments of each competition, or everything when unwindowed. A row
 *  with no `ago` predates the field and is dropped rather than guessed at. */
function inWindow<T extends { ago?: number }>(rows: T[] | undefined, window: SeasonWindow | undefined): T[] {
  if (!rows) return [];
  if (window === undefined) return rows;
  return rows.filter((r) => r.ago !== undefined && r.ago < window);
}

export async function getManagers(nationality?: string, window?: SeasonWindow): Promise<Manager[]> {
  const { managers, leagues } = await load();
  const latestByCountry = latestLeagueSeasonByCountry(leagues);

  return managers
    .filter((m) => !nationality || nationality === 'ALL' || m.nationality === nationality)
    .map((m) => {
      const titles = m.titles ?? [];
      const lgLast =
        m.lgLast ??
        (titles.some((t) => t.last !== undefined)
          ? titles.filter((t) => t.last).length
          : titles.filter((t) => latestByCountry.get(t.country) === t.season).length);
      // With a window active every total is recounted from the trophy lists, each against its own
      // competition's clock. Without one the bake's precomputed totals are used as-is — identical
      // results, and no per-row work.
      const windowed = window !== undefined;
      const medalsIn = inWindow(m.medals, window);
      return {
        userId: m.userId,
        login: m.userName,
        c: m.nationality,
        team: '',
        lg: windowed ? inWindow(titles, window).length : m.lg,
        main: windowed ? inWindow(m.cupsMain, window).length : (m.main ?? 0),
        sec: windowed ? inWindow(m.cupsSec, window).length : (m.sec ?? 0),
        hm: windowed ? inWindow(m.masters, window).length : (m.hm ?? 0),
        // Seasonal Cups count like everything else now: each is its own perpetual tournament, so a
        // window of N means its N most recent instalments.
        sn: windowed ? inWindow(m.seasonal, window).length : (m.sn ?? 0),
        wc: windowed ? inWindow(m.worldCup, window).length : (m.wc ?? 0),
        wcSilver: windowed ? medalsIn.filter((x) => x.place === 2).length : (m.wcSilver ?? 0),
        wcBronze: windowed ? medalsIn.filter((x) => x.place === 3).length : (m.wcBronze ?? 0),
        oth: 0,
        lgLast,
        mainLast: m.mainLast ?? (m.cupsMain ?? []).filter((c) => c.last).length,
        secLast: m.secLast ?? (m.cupsSec ?? []).filter((c) => c.last).length,
        hmLast: m.hmLast ?? (m.masters ?? []).filter((c) => c.last).length,
        snLast: m.snLast ?? (m.seasonal ?? []).filter((c) => c.last).length,
        wcLast: m.wcLast ?? (m.worldCup ?? []).filter((c) => c.last).length,
      };
    });
}

/**
 * A manager's full trophy cabinet.
 *
 * `championsLabel` builds the "<country> champions" heading — the ONE user-facing sentence this
 * data layer composes, so the caller passes the translated form rather than the module reaching
 * for a language it has no business knowing about. Every other label here is a proper name that
 * came out of the bake and stays exactly as Hattrick spells it.
 */
export async function getCabinet(
  userId: number,
  championsLabel: (country: string) => string = (c) => `${c} champions`,
  window?: SeasonWindow,
): Promise<TrophyCabinet> {
  const { managers, leagues } = await load();
  const m = managers.find((x) => x.userId === userId);
  // Mirror getManagers' league fallback so an expanded cabinet stays consistent with the chart
  // under "Reigning only" even before a re-bake (cups need the bake — no `last`, no fallback).
  const latestByCountry = latestLeagueSeasonByCountry(leagues);
  // Same window as the row's total, or the cabinet would list trophies the count doesn't include.
  const champ = inWindow(m?.titles, window).map((t) => ({
    main: championsLabel(t.country),
    sub: t.club,
    teamId: t.teamId,
    season: 'S' + t.season,
    last: t.last ?? latestByCountry.get(t.country) === t.season,
    flag: leagueFlagUrl(t.leagueId),
  }));
  const cupItems = (cups?: RawCup[]) =>
    inWindow(cups, window).map((t) => ({ main: t.cup, sub: t.club, teamId: t.teamId, season: 'S' + t.season, last: t.last, flag: leagueFlagUrl(t.leagueId) }));
  // `other` carries the Hattrick Masters, `seasonal` the Seasonal Cups, `worldCup` the World Cup
  // (senior + youth) — each its own category (see bake.ts / sync/masters.ts / sync/seasonal.ts /
  // sync/worldCup.ts). All three are country-less, so no flag.
  // National-team rows flag by id first, name second — see flags.ts nationFlagUrl for why.
  const nationFlag = nationFlagUrl;
  const nationalItems = (cups?: RawCup[]) =>
    inWindow(cups, window).map((t) => ({ main: t.cup, sub: t.club, teamId: t.teamId, season: 'S' + t.season, last: t.last, flag: nationFlag(t.club, t.leagueId) }));
  const medalItems = (place: number) =>
    inWindow(m?.medals, window)
      .filter((x) => x.place === place)
      .map((x) => ({ main: x.cup, sub: x.nation, season: 'S' + x.season, flag: nationFlag(x.nation, x.leagueId) }));
  return {
    champ, main: cupItems(m?.cupsMain), sec: cupItems(m?.cupsSec),
    other: cupItems(m?.masters),
    seasonal: cupItems(m?.seasonal),
    worldCup: nationalItems(m?.worldCup),
    silver: medalItems(2), bronze: medalItems(3),
  };
}

export async function getWinners(leagueId: string): Promise<Winner[]> {
  const { leagues, managers } = await load();
  const l = leagues.find((x) => String(x.leagueId) === leagueId);
  if (!l) return [];
  const natByLogin = new Map(managers.map((m) => [m.userName, m.nationality]));
  return l.champions.map((c) => ({ ...c, nationality: natByLogin.get(c.manager) }));
}

/**
 * World Cup (senior + youth) — the champion is a NATION, not a manager/club, so it's a completely
 * separate shape from Winner. No CHPP path exists for national-team competitions (cupmatches
 * returns nothing); the full record was scraped once from World/WorldCup/History.aspx
 * (see server/sync/worldCup.ts). The youth bracket was "U20" through edition 31, "U21" after.
 */
export interface WorldCupEdition {
  edition: number;
  ageGroup?: string;
  host: string;
  finished: string | null; // "DD.MM.YYYY", null while ongoing
  champion: string | null; // nation name, null while ongoing
  runnerUp: string | null;
  thirdFourth: string[];
  /** Set for the regional cups (scraped from Cup.aspx podium links); absent for World Cup editions,
   *  whose History.aspx source carries names only. Flags fall back to the name there. */
  championLeagueId?: number;
  runnerUpLeagueId?: number;
  thirdFourthLeagueIds?: number[];
  /** The manager coaching the champion nation when the edition finished (cross-referenced from
   *  NTFormerCoaches.aspx — see sync/worldCup.ts). Undefined when unattributed: "Retired user"
   *  tenure, no tenure recorded that far back, or the nation's team id never resolved. */
  coachUserId?: number;
  coach?: string;
  coachNationality?: string;
  /** The coach who lost the final, resolved by the same tenure rule and equally often missing. */
  runnerUpCoachUserId?: number;
  runnerUpCoach?: string;
  runnerUpCoachNationality?: string;
  /** The losing semi-finalists' coaches, INDEX-ALIGNED with `thirdFourth`. An empty object is an
   *  attributable-nation-with-unattributable-coach, kept in place so the indices still line up. */
  thirdFourthCoaches?: Array<{ userId?: number; name?: string; nationality?: string }>;
}
/**
 * A regional national-team cup — Africa / America / Asia and Oceania / Europe / Nations Cup (see
 * server/sync/ntCups.ts). Same nature as the World Cup, but perpetual: a champion per SEASON rather
 * than a numbered edition, which is the only reason it isn't just more WorldCupEditions.
 */
export interface RegionalCupSeason {
  season: number;
  host: string;
  finished: string | null; // "DD-MM-YYYY HH:MM" as printed, null while the season is running
  status?: string;
  champion: string | null;
  runnerUp: string | null;
  thirdFourth: string[];
  /** Podium league ids, index-aligned with `thirdFourth` — the reliable flag key (see flags.ts). */
  championLeagueId?: number;
  runnerUpLeagueId?: number;
  thirdFourthLeagueIds?: number[];
  coachUserId?: number;
  coach?: string;
  coachNationality?: string;
  /** The rest of the podium's coaches — same shape and same caveats as on WorldCupEdition. */
  runnerUpCoachUserId?: number;
  runnerUpCoach?: string;
  runnerUpCoachNationality?: string;
  thirdFourthCoaches?: Array<{ userId?: number; name?: string; nationality?: string }>;
}
export interface RegionalCupRoll {
  cupId: number;
  cupName: string;
  isYouth: boolean;
  seasons: RegionalCupSeason[];
}
export interface WorldCupHistory {
  senior: WorldCupEdition[];
  youth: WorldCupEdition[];
  /** Absent in bakes that predate the regional cups — treated as an empty list. */
  regional?: RegionalCupRoll[];
}

const EMPTY_WC: WorldCupHistory = { senior: [], youth: [], regional: [] };

let worldCupBundle: Promise<WorldCupHistory> | null = null;
export async function getWorldCup(): Promise<WorldCupHistory> {
  if (!worldCupBundle) {
    worldCupBundle = fetch('/data/worldcup.json')
      .then((r) => (r.ok ? (r.json() as Promise<WorldCupHistory>) : EMPTY_WC))
      .catch(() => EMPTY_WC);
  }
  return worldCupBundle;
}

/**
 * Every national-team competition as one uniform list for the National trophies view: the World
 * Cup brackets keyed by edition, each regional cup keyed by season. Regional seasons are mapped
 * onto the same row shape (`edition` carries the season number) so one table renders them all —
 * `unitLabel` is what tells the reader which number they're looking at.
 */
export interface NationalCompetition {
  key: string;
  /** Cup names as they appear in a manager's baked record — the join key for per-coach medals.
   *  Usually one, and NOT always the display label (the youth World Cup bakes as "World Cup (Youth)"). */
  matchCups: string[];
  /** Full name, e.g. "U21 Europe Cup" — always shown on the champions list itself. */
  label: string;
  /** Bracket-independent name, e.g. "Europe Cup". Lets the senior and U21 lists read as the same
   *  set of competitions, and lets a bracket switch stay on the competition you were looking at. */
  shortLabel: string;
  isYouth: boolean;
  unitLabel: string;
  rows: WorldCupEdition[];
}

export async function getNationalCompetitions(): Promise<NationalCompetition[]> {
  const wc = await getWorldCup();
  const comps: NationalCompetition[] = [
    { key: 'senior', matchCups: ['World Cup'], label: 'World Cup', shortLabel: 'World Cup', isYouth: false, unitLabel: 'Ed.', rows: wc.senior },
    { key: 'youth', matchCups: ['World Cup (Youth)'], label: 'World Cup (Youth U20/U21)', shortLabel: 'World Cup', isYouth: true, unitLabel: 'Ed.', rows: wc.youth },
  ];
  for (const cup of wc.regional ?? []) {
    comps.push({
      key: `cup-${cup.cupId}`,
      matchCups: [cup.cupName],
      label: cup.cupName,
      shortLabel: cup.cupName.replace(/^U21\s+/, ''),
      isYouth: cup.isYouth,
      unitLabel: 'Season',
      rows: cup.seasons.map((s) => ({
        edition: s.season,
        host: s.host,
        finished: s.finished,
        champion: s.champion,
        runnerUp: s.runnerUp,
        thirdFourth: s.thirdFourth,
        championLeagueId: s.championLeagueId,
        runnerUpLeagueId: s.runnerUpLeagueId,
        thirdFourthLeagueIds: s.thirdFourthLeagueIds,
        coachUserId: s.coachUserId,
        coach: s.coach,
        coachNationality: s.coachNationality,
        runnerUpCoachUserId: s.runnerUpCoachUserId,
        runnerUpCoach: s.runnerUpCoach,
        runnerUpCoachNationality: s.runnerUpCoachNationality,
        thirdFourthCoaches: s.thirdFourthCoaches,
      })),
    });
  }
  return comps.filter((c) => c.rows.length > 0);
}

/** One podium a coach took, for the expanded row. */
export interface CoachMedalResult {
  cup: string;
  season: number; // the EDITION for World Cup rows, a real season for the regional cups
  nation: string;
  place: number;
}

/** A coach's podium record in national-team competitions. */
export interface CoachMedals {
  userId: number;
  name: string;
  nationality?: string;
  g: number;
  s: number;
  b: number;
  /** The individual podiums behind those totals, best placing first. */
  results: CoachMedalResult[];
}

/**
 * Medal table by COACH, for the given competitions (matched on the cup names a manager's record
 * carries). Built from managers.json rather than worldcup.json: the rolls of honour name the
 * champion's coach only, while a manager's own record holds every podium place they took.
 *
 * World Cup editions therefore show golds but no medals — their History.aspx source never carried
 * a runner-up coach, unlike the regional cups scraped from the podium.
 */
export async function getCoachMedals(matchCups: string[]): Promise<CoachMedals[]> {
  const { managers } = await load();
  const want = new Set(matchCups);
  const out: CoachMedals[] = [];
  for (const m of managers) {
    const titles = (m.worldCup ?? []).filter((t) => want.has(t.cup));
    const medals = (m.medals ?? []).filter((x) => want.has(x.cup));
    const g = titles.length;
    const s = medals.filter((x) => x.place === 2).length;
    const b = medals.filter((x) => x.place === 3).length;
    if (g + s + b === 0) continue;
    const results: CoachMedalResult[] = [
      ...titles.map((t) => ({ cup: t.cup, season: t.season, nation: t.club, place: 1 })),
      ...medals.map((x) => ({ cup: x.cup, season: x.season, nation: x.nation, place: x.place })),
    ].sort((a, b2) => a.place - b2.place || b2.season - a.season || a.cup.localeCompare(b2.cup));
    out.push({ userId: m.userId, name: m.userName, nationality: m.nationality, g, s, b, results });
  }
  return out.sort((a, b2) => b2.g - a.g || b2.s - a.s || b2.b - a.b || a.name.localeCompare(b2.name));
}

/**
 * National Coach elections — who a country's community voted to lead their national team for a
 * given World Cup cycle, independent of whether that country ever won anything. No CHPP path
 * exists; scraped once per country from World/Elections/History.aspx (see server/sync/elections.ts).
 * A country can list the SAME edition twice (a mid-cycle re-election) — that's intentional, not a
 * duplicate to collapse.
 */
export interface ElectionResult {
  leagueId: number;
  countryName: string;
  edition: number;
  host: string;
  /** The U20/U21 National Coach election rather than the senior one — both are published on the
   *  same page, in two tables. Absent means senior (the bake only writes it when true). */
  isYouth?: boolean;
  winnerUserId?: number;
  winner?: string; // undefined = "A former user" (unattributed sentinel)
  winnerNationality?: string;
  votes?: string; // raw "37 (44%)" text
}

let electionsBundle: Promise<ElectionResult[]> | null = null;
function loadElections() {
  if (!electionsBundle) {
    electionsBundle = fetch('/data/elections.json')
      .then((r) => (r.ok ? (r.json() as Promise<ElectionResult[]>) : []))
      .catch(() => []);
  }
  return electionsBundle;
}

export async function getElectionCountries(): Promise<Country[]> {
  const rows = await loadElections();
  const seen = new Map<number, string>();
  for (const r of rows) if (!seen.has(r.leagueId)) seen.set(r.leagueId, r.countryName);
  return [...seen.entries()].map(([code, name]) => ({ code: String(code), name })).sort((a, b) => a.name.localeCompare(b.name));
}

export async function getElections(leagueId: string): Promise<ElectionResult[]> {
  const rows = await loadElections();
  return rows.filter((r) => String(r.leagueId) === leagueId).sort((a, b) => b.edition - a.edition);
}

/** Every election result, for the global "most elected" leaderboard (not scoped to one country). */
export async function getAllElections(): Promise<ElectionResult[]> {
  return loadElections();
}

/**
 * One election a manager won, placed in time.
 *
 * The scraped roll carries a World Cup EDITION, never a season and never a date — so the cycle's
 * own finishing date is borrowed from worldcup.json (which covers every edition the elections
 * span) to give the timeline a real anchor. It is the date the cycle ENDED, not the date of the
 * vote, which is why it's labelled as the World Cup's date and not the election's.
 */
export interface ElectionEntry {
  leagueId: number;
  countryName: string;
  edition: number;
  host: string;
  isYouth: boolean;
  votes?: string;
  finished: string | null; // "DD.MM.YYYY", null while that cycle is still running
  /** What the mandate produced — see `ElectionTrophy` and `matchTrophies`. Empty for most. */
  trophies: ElectionTrophy[];
}

/** A national-team result won under one election's mandate. */
export interface ElectionTrophy {
  cup: string;
  place: number; // 1 = won it, 2 = runner-up, 3 = losing semi-finalist
  /**
   * How the result was tied to this election:
   *   true  — the World Cup this mandate was literally for (edition == edition, an exact join).
   *   false — a regional cup whose final fell inside the mandate's date window.
   * The UI marks the second kind, because "during the cycle" is a weaker claim than "this cup".
   */
  exact: boolean;
}

/** One manager's election record: how often elected, and which countries elected them. */
export interface ElectionLeader {
  userId?: number;
  name: string;
  nationality?: string;
  count: number;
  /** The same total, split by bracket — senior National Coach elections and the U20/U21 ones,
   *  which Hattrick publishes in a second table on the same page. */
  senior: number;
  youth: number;
  /** Countries that elected them and how often, most-elected first. A coach can serve several over
   *  a career — it's the national team's community that votes, not their own country's — and can be
   *  re-elected by the same one across cycles, so the count carries real information. Senior and
   *  U21 elections for one country both land in the same tally. */
  countries: Array<{ country: string; count: number }>;
  /** Every election they won, newest cycle first. */
  elections: ElectionEntry[];
  /**
   * National-team results that no election of theirs can account for — overwhelmingly because the
   * election record only starts at World Cup 16, while the competitions go back to edition 1.
   * Without these the timeline reads as a complete career and quietly denies real trophies:
   * HPE-regia5 won the World Cup with Norge in cycle 15 and was elected by Norway in 17, 18 and 19,
   * so every Norway row would otherwise show no result at all.
   */
  otherResults: OtherResult[];
}

/** A trophy or medal that falls outside every recorded mandate. */
export interface OtherResult {
  cup: string;
  place: number;
  nation: string;
  /** The EDITION for World Cup rows, a real season for the regional cups — `isWorldCupResult` says
   *  which, so the UI can label it "WC 15" rather than "S15". */
  season: number;
  isWorldCupResult: boolean;
}

/** How many of a nationality's managers the expanded row lists. */
export const ELECTION_NATION_TOP_N = 10;

/** A nationality's pooled election record. */
export interface ElectionNation {
  nationality: string;
  managers: number; // distinct managers of that nationality who were ever elected
  count: number;
  senior: number;
  youth: number;
  /** Its most-elected managers, best first, capped at ELECTION_NATION_TOP_N. */
  top: Array<{ name: string; userId?: number; count: number; youth: number }>;
}

/**
 * Both aggregations plus the rows neither can honestly count, from one pass.
 *
 * Elections are joined to managers BY NAME, like every other name-based join in these views. Two
 * kinds of row can't be attributed and are reported rather than silently dropped:
 * `unattributed` (Hattrick prints "A former user" instead of a name) and `withoutNationality`
 * (a named winner whose nationality never resolved). The latter is deliberately NOT pooled into an
 * "Unknown" nation — at ~a fifth of all named winners it would top the nationality ranking and
 * mean nothing.
 */
export interface ElectionAggregates {
  leaders: ElectionLeader[];
  nations: ElectionNation[];
  unattributed: number;
  withoutNationality: number;
}

/** "DD.MM.YYYY" (World Cup) or "DD-MM-YYYY HH:MM" (regional cups) → epoch ms, or null. */
function parseHtDate(s: string | null | undefined): number | null {
  const m = (s ?? '').match(/(\d{1,2})[.\-/](\d{1,2})[.\-/](\d{4})/);
  return m ? Date.UTC(Number(m[3]), Number(m[2]) - 1, Number(m[1])) : null;
}

/** A national-team result flattened out of a manager's baked record. */
interface NationalResult {
  cup: string;
  season: number; // the EDITION for World Cup rows, a real season for the regional cups
  nation: string; // native name, "U21 "-prefixed on the youth side
  leagueId?: number; // 0/absent for the World Cup, which is nobody's league
  place: number;
  isYouth: boolean;
}

const isYouthCup = (cup: string) => cup.startsWith('U21 ') || cup === 'World Cup (Youth)';
const isWorldCup = (cup: string) => cup === 'World Cup' || cup === 'World Cup (Youth)';

/**
 * Does a national result belong to the nation that held this election?
 *
 * Regional results carry the nation's leagueId and join on it directly. World Cup results carry
 * leagueId 0 (the World Cup is nobody's league) and only a NATIVE nation name ("Nederland"), while
 * the election carries an English one ("Netherlands") — so those reconcile through the ISO code,
 * the same bridge `nationFlagUrl` uses for exactly this mismatch.
 */
function sameNation(r: NationalResult, leagueId: number): boolean {
  if (r.leagueId) return r.leagueId === leagueId;
  const iso = NATIONALITY_ISO[r.nation.replace(/^U21\s+/, '')];
  return !!iso && iso === LEAGUE_ISO[leagueId];
}

export async function getElectionAggregates(): Promise<ElectionAggregates> {
  const [rows, wc, { managers }] = await Promise.all([loadElections(), getWorldCup(), load()]);
  // Elections span editions 16–41 and worldcup.json carries every one of them, so this join is
  // total in practice; a miss degrades to a dateless row rather than dropping the election.
  const finishedByEdition = new Map(wc.senior.map((e) => [e.edition, e.finished]));

  // A mandate's window: from the previous cycle's final to its own. Editions are consecutive, so
  // the previous edition's finish is the natural start; the running cycle has no end yet.
  const editionsAsc = wc.senior.slice().sort((a, b) => a.edition - b.edition);
  const cycleWindow = new Map<number, { from: number; to: number }>();
  editionsAsc.forEach((e, i) => {
    const prev = i > 0 ? parseHtDate(editionsAsc[i - 1]!.finished) : null;
    cycleWindow.set(e.edition, { from: prev ?? -Infinity, to: parseHtDate(e.finished) ?? Infinity });
  });

  // When each regional-cup season's final was played, so a per-season trophy can be placed inside
  // a per-edition mandate.
  const regionalFinal = new Map<string, number>();
  for (const cup of wc.regional ?? []) {
    for (const s of cup.seasons) {
      const ms = parseHtDate(s.finished);
      if (ms != null) regionalFinal.set(`${cup.cupName}|${s.season}`, ms);
    }
  }

  // Every manager's national-team results — titles and podium places alike — in one flat list.
  const resultsByUser = new Map<number, NationalResult[]>();
  for (const m of managers) {
    const out: NationalResult[] = [];
    for (const t of m.worldCup ?? [])
      out.push({ cup: t.cup, season: t.season, nation: t.club, leagueId: t.leagueId, place: 1, isYouth: isYouthCup(t.cup) });
    for (const x of m.medals ?? [])
      out.push({ cup: x.cup, season: x.season, nation: x.nation, leagueId: x.leagueId, place: x.place, isYouth: isYouthCup(x.cup) });
    if (out.length) resultsByUser.set(m.userId, out);
  }

  /**
   * What one election's mandate produced for the nation that voted.
   *
   * Only ever looks at results ALREADY attributed to this manager (by coaching tenure at the
   * final), so a title can't be credited to someone who had been replaced — the question here is
   * narrower: of the trophies this manager did win with this nation, which fall under this mandate.
   */
  // Which of a manager's results some mandate accounted for, so the remainder can be surfaced
  // rather than silently dropped.
  const claimed = new Map<number, Set<number>>();

  const matchTrophies = (userId: number | undefined, leagueId: number, edition: number, isYouth: boolean): ElectionTrophy[] => {
    const all = userId ? resultsByUser.get(userId) : undefined;
    if (!all || userId == null) return [];
    const win = cycleWindow.get(edition);
    const out: ElectionTrophy[] = [];
    all.forEach((r, ix) => {
      if (r.isYouth !== isYouth || !sameNation(r, leagueId)) return;
      let hit = false;
      if (isWorldCup(r.cup)) {
        // Exact: for World Cup rows the bake stores the edition in `season` (see sync/bake.ts).
        if (r.season === edition) hit = out.push({ cup: r.cup, place: r.place, exact: true }) > 0;
      } else if (win) {
        const ms = regionalFinal.get(`${r.cup}|${r.season}`);
        if (ms != null && ms > win.from && ms <= win.to) hit = out.push({ cup: r.cup, place: r.place, exact: false }) > 0;
      }
      if (hit) {
        let s = claimed.get(userId);
        if (!s) claimed.set(userId, (s = new Set()));
        s.add(ix);
      }
    });
    // The World Cup itself first, then better placings — the headline result leads.
    return out.sort((a, b) => Number(b.exact) - Number(a.exact) || a.place - b.place || a.cup.localeCompare(b.cup));
  };

  const byUser = new Map<string, ElectionLeader & { byCountry: Map<string, number> }>();
  let unattributed = 0;
  for (const r of rows) {
    if (!r.winner) {
      unattributed++;
      continue;
    }
    let e = byUser.get(r.winner);
    if (!e) {
      // otherResults is filled in the mapping pass below, once every mandate has had its say.
      e = { name: r.winner, userId: r.winnerUserId, nationality: r.winnerNationality, count: 0, senior: 0, youth: 0, countries: [], elections: [], otherResults: [], byCountry: new Map() };
      byUser.set(r.winner, e);
    }
    const isYouth = !!r.isYouth;
    e.count++;
    if (isYouth) e.youth++;
    else e.senior++;
    e.userId ??= r.winnerUserId;
    e.nationality ??= r.winnerNationality;
    e.byCountry.set(r.countryName, (e.byCountry.get(r.countryName) ?? 0) + 1);
    e.elections.push({
      leagueId: r.leagueId,
      countryName: r.countryName,
      edition: r.edition,
      host: r.host,
      isYouth,
      votes: r.votes,
      finished: finishedByEdition.get(r.edition) ?? null,
      trophies: matchTrophies(r.winnerUserId, r.leagueId, r.edition, isYouth),
    });
  }

  const leaders = [...byUser.values()]
    .map(({ byCountry, ...e }) => ({
      ...e,
      countries: [...byCountry.entries()]
        .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
        .map(([country, count]) => ({ country, count })),
      // Newest cycle first, matching every other roll in the app. A country can re-elect mid-cycle,
      // and the senior and U21 votes of one cycle both land here, so the same edition legitimately
      // appears more than once — order those by bracket then country to stay stable.
      elections: e.elections
        .slice()
        .sort((a, b) => b.edition - a.edition || Number(a.isYouth) - Number(b.isYouth) || a.countryName.localeCompare(b.countryName)),
      otherResults: (e.userId == null ? [] : resultsByUser.get(e.userId) ?? [])
        .map((r, ix) => ({ r, ix }))
        .filter(({ ix }) => !claimed.get(e.userId!)?.has(ix))
        .map(({ r }) => ({ cup: r.cup, place: r.place, nation: r.nation, season: r.season, isWorldCupResult: isWorldCup(r.cup) }))
        .sort((a, b) => a.place - b.place || b.season - a.season || a.cup.localeCompare(b.cup)),
    }))
    .sort((a, b) => b.count - a.count || a.name.localeCompare(b.name));

  const byNation = new Map<string, ElectionNation>();
  let withoutNationality = 0;
  for (const l of leaders) {
    if (!l.nationality) {
      withoutNationality += l.count;
      continue;
    }
    let n = byNation.get(l.nationality);
    if (!n) {
      n = { nationality: l.nationality, managers: 0, count: 0, senior: 0, youth: 0, top: [] };
      byNation.set(l.nationality, n);
    }
    n.managers++;
    n.count += l.count;
    n.senior += l.senior;
    n.youth += l.youth;
    // `leaders` is already sorted by election count, so each nation's contributors arrive in
    // order — the cap alone is enough, no second sort.
    if (n.top.length < ELECTION_NATION_TOP_N) n.top.push({ name: l.name, userId: l.userId, count: l.count, youth: l.youth });
  }
  const nations = [...byNation.values()].sort((a, b) => b.count - a.count || a.nationality.localeCompare(b.nationality));

  return { leaders, nations, unattributed, withoutNationality };
}
