/**
 * Data layer for the Aggregate Stats views — STATIC build.
 *
 * Loads two baked JSON files once (public/data, regenerated by server scripts/bake-static.ts)
 * and serves everything client-side, so the deployed site needs no backend or database.
 *
 * Backend honesty: only top-division LEAGUE titles exist (no cup/other trophies), so `cup`/`oth`
 * are 0 and a manager's cabinet holds only championships. Data is a frozen snapshot — re-bake +
 * re-deploy to refresh.
 */

import { leagueFlagUrl, nationFlagUrl } from './flags.js';

export interface Country {
  code: string;
  name: string;
}

export interface Manager {
  userId: number;
  login: string;
  c: string;
  team: string;
  lg: number;
  main: number; // main national cup wins (attributed)
  sec: number; // secondary/consolation cup wins (attributed)
  hm: number; // Hattrick Masters wins (the global champions-of-champions cup)
  sn: number; // Seasonal Cups wins (global recurring tournaments, e.g. Supporter Week Trophy)
  /** "National trophies": titles won as a NATIONAL COACH. The World Cup (senior + youth) today —
   *  the regional and alternate cups will land in this same bucket (see sync/worldCup.ts). The
   *  `wc`/`worldCup` names are the baked wire format and stay as they are. */
  wc: number;
  /** Podium places short of the title, in those same national competitions. Never folded into `wc`:
   *  a runner-up is not a trophy, so titles-only totals stay exactly what they always were. */
  wcSilver: number;
  wcBronze: number;
  oth: number;
  lgLast: number; // reigning league titles (current champion of that league)
  mainLast: number; // reigning main-cup titles (current holder of that cup)
  secLast: number; // reigning secondary/consolation-cup titles
  hmLast: number; // reigning Hattrick Masters title (holder of the most recent edition)
  snLast: number; // reigning Seasonal Cups titles (holder of the most recent edition)
  wcLast: number; // reigning World Cup title(s) (per bracket — senior and youth reign separately)
}

export interface TrophyItem {
  main: string;
  sub: string;
  season: string;
  /** The winning club's real Hattrick id, when the pipeline resolved one — links `sub` out to
   *  hattrick.org. Absent for reconstructed placeholders and for the World Cup, whose "club" is a
   *  nation with no team id at all. */
  teamId?: number;
  last?: boolean; // the reigning/most-recent trophy of its competition
  flag?: string | null; // country-flag URL (by leagueId); null for the country-less Masters/World Cup
}

export interface TrophyCabinet {
  champ: TrophyItem[];
  main: TrophyItem[];
  sec: TrophyItem[];
  other: TrophyItem[]; // the Hattrick Masters
  seasonal: TrophyItem[]; // Seasonal Cups (Supporter Week Trophy)
  worldCup: TrophyItem[]; // "National trophies" — titles won as a national coach (World Cup today)
  /** Podium places short of the title, in those same national competitions. Kept apart from
   *  `worldCup` so a medal is never mistaken for a trophy — the UI shows them as their own groups. */
  silver: TrophyItem[];
  bronze: TrophyItem[];
}

export interface Winner {
  season: number;
  club: string;
  manager: string;
  /** Manager's nationality (country name, matches NATIONALITY_ISO in flags.ts), joined by login name
   *  from managers.json — best-effort like the rest of the retro views' name-based joins. */
  nationality?: string;
  /** Real Hattrick ids, present only where the sync pipeline actually resolved them — link out to
   *  hattrick.org when set, render as plain text otherwise. Coverage varies a lot by category:
   *  league/national-cup champions rarely have a stored teamId (the manager is attributed directly,
   *  without ever resolving a team), while Masters and Seasonal Cups usually do (see bake.ts). */
  teamId?: number;
  userId?: number;
}

export type CupWinner = Winner;

export interface CupRoll {
  cupId: number;
  cupName: string;
  isMain: boolean;
  cupLevel: number;
  cupLevelIndex: number;
  winners: CupWinner[];
}

export interface CupCountry {
  leagueId: number;
  country: string;
  cups: CupRoll[];
}

interface RawCup {
  country: string;
  leagueId?: number;
  season: number;
  club: string;
  teamId?: number;
  cup: string;
  last?: boolean;
}
interface RawManager {
  userId: number;
  userName: string;
  nationality: string;
  lg: number;
  main: number;
  sec: number;
  hm?: number;
  sn?: number;
  wc?: number;
  wcSilver?: number;
  wcBronze?: number;
  lgLast?: number;
  mainLast?: number;
  secLast?: number;
  hmLast?: number;
  snLast?: number;
  wcLast?: number;
  titles: Array<{ country: string; leagueId?: number; season: number; club: string; teamId?: number; last?: boolean }>;
  cupsMain: RawCup[];
  cupsSec: RawCup[];
  masters?: RawCup[];
  seasonal?: RawCup[];
  worldCup?: RawCup[];
  /** One entry per podium place short of the title: place 2 = silver, 3 = bronze. */
  medals?: Array<{ cup: string; season: number; nation: string; leagueId?: number; place: number }>;
}
interface RawLeague {
  leagueId: number;
  country: string;
  champions: Array<{ season: number; club: string; manager: string }>;
}

let bundle: Promise<{ managers: RawManager[]; leagues: RawLeague[] }> | null = null;
function load() {
  if (!bundle) {
    bundle = Promise.all([
      fetch('/data/managers.json').then((r) => r.json() as Promise<RawManager[]>),
      fetch('/data/leagues.json').then((r) => r.json() as Promise<RawLeague[]>),
    ]).then(([managers, leagues]) => ({ managers, leagues }));
  }
  return bundle;
}

// Cups load lazily on their own — the Cup winners view is the only consumer, and cups.json is
// large, so we don't pull it into the initial bundle. Missing file (older bake) → empty list.
let cupsBundle: Promise<CupCountry[]> | null = null;
function loadCups() {
  if (!cupsBundle) {
    cupsBundle = fetch('/data/cups.json')
      .then((r) => (r.ok ? (r.json() as Promise<CupCountry[]>) : []))
      .catch(() => []);
  }
  return cupsBundle;
}

export async function getCupCountries(): Promise<Country[]> {
  const cups = await loadCups();
  return cups.map((c) => ({ code: String(c.leagueId), name: c.country }));
}

/** International cupId of the Supporter Week Trophy — mirrors server/src/sync/seasonal.ts. Every
 *  other entry in seasonal.json is a "Heroes/Titans of YYYY Trophy" (Generation) cohort. */
export const SUPPORTER_WEEK_CUP_ID = 2108472;

interface RawSeasonalCup {
  cupId: number;
  cupName: string;
  winners: Array<{ season: number; club: string; manager: string }>;
}
let seasonalBundle: Promise<RawSeasonalCup[]> | null = null;
function loadSeasonal() {
  if (!seasonalBundle) {
    seasonalBundle = fetch('/data/seasonal.json')
      .then((r) => (r.ok ? (r.json() as Promise<RawSeasonalCup[]>) : []))
      .catch(() => []);
  }
  return seasonalBundle;
}

export interface SeasonalCupRoll {
  cupId: number;
  cupName: string;
  isGeneration: boolean; // false for Supporter Week Trophy, true for every "Heroes/Titans of YYYY" cohort
  winners: Winner[];
}

/** Every Seasonal Cup's roll of honour — Supporter Week Trophy plus all "Heroes/Titans of YYYY"
 *  (Generation) cohorts, each its own perpetual tournament (see sync/seasonal.ts). */
export async function getSeasonalCups(): Promise<SeasonalCupRoll[]> {
  const [raw, { managers }] = await Promise.all([loadSeasonal(), load()]);
  const natByLogin = new Map(managers.map((m) => [m.userName, m.nationality]));
  return raw.map((c) => ({
    cupId: c.cupId,
    cupName: c.cupName,
    isGeneration: c.cupId !== SUPPORTER_WEEK_CUP_ID,
    winners: c.winners.map((w) => ({ ...w, nationality: natByLogin.get(w.manager) })),
  }));
}

let mastersBundle: Promise<Array<{ season: number; club: string; manager: string }>> | null = null;
function loadMasters() {
  if (!mastersBundle) {
    mastersBundle = fetch('/data/masters.json')
      .then((r) => (r.ok ? (r.json() as Promise<Array<{ season: number; club: string; manager: string }>>) : []))
      .catch(() => []);
  }
  return mastersBundle;
}

/** The Hattrick Masters roll of honour — international, no country (see sync/masters.ts). */
export async function getMastersWinners(): Promise<Winner[]> {
  const [raw, { managers }] = await Promise.all([loadMasters(), load()]);
  const natByLogin = new Map(managers.map((m) => [m.userName, m.nationality]));
  return raw.map((w) => ({ ...w, nationality: natByLogin.get(w.manager) }));
}

export async function getCups(leagueId: string): Promise<CupRoll[]> {
  const [cups, { managers }] = await Promise.all([loadCups(), load()]);
  const country = cups.find((c) => String(c.leagueId) === leagueId);
  if (!country) return [];
  const natByLogin = new Map(managers.map((m) => [m.userName, m.nationality]));
  return country.cups.map((c) => ({ ...c, winners: c.winners.map((w) => ({ ...w, nationality: natByLogin.get(w.manager) })) }));
}

export async function getNationalities(): Promise<Country[]> {
  const { managers } = await load();
  const counts = new Map<string, number>();
  for (const m of managers) counts.set(m.nationality, (counts.get(m.nationality) ?? 0) + 1);
  return [...counts.entries()]
    .filter(([n]) => n && n !== 'Unknown')
    .sort((a, b) => b[1] - a[1])
    .map(([nationality, n]) => ({ code: nationality, name: `${nationality} (${n})` }));
}

export async function getLeagues(): Promise<Country[]> {
  const { leagues } = await load();
  return leagues.map((l) => ({ code: String(l.leagueId), name: l.country }));
}

/**
 * Fallback for bakes that predate the per-item `last` flag: each country's latest league season.
 * Each country runs its own season clock, so the reigning season is per-country. Lets league
 * reigning resolve client-side before a re-bake; baked `last` flags take precedence when present.
 */
function latestLeagueSeasonByCountry(leagues: RawLeague[]): Map<string, number> {
  const latest = new Map<string, number>();
  for (const l of leagues)
    for (const c of l.champions) {
      const cur = latest.get(l.country);
      if (cur === undefined || c.season > cur) latest.set(l.country, c.season);
    }
  return latest;
}

export async function getManagers(nationality?: string): Promise<Manager[]> {
  const { managers, leagues } = await load();
  const latestByCountry = latestLeagueSeasonByCountry(leagues);

  return managers
    .filter((m) => !nationality || nationality === 'ALL' || m.nationality === nationality)
    .map((m) => {
      const titles = m.titles ?? [];
      const lgLast =
        m.lgLast ??
        (titles.some((t) => t.last !== undefined)
          ? titles.filter((t) => t.last).length
          : titles.filter((t) => latestByCountry.get(t.country) === t.season).length);
      return {
        userId: m.userId,
        login: m.userName,
        c: m.nationality,
        team: '',
        lg: m.lg,
        main: m.main ?? 0,
        sec: m.sec ?? 0,
        hm: m.hm ?? 0,
        sn: m.sn ?? 0,
        wc: m.wc ?? 0,
        wcSilver: m.wcSilver ?? 0,
        wcBronze: m.wcBronze ?? 0,
        oth: 0,
        lgLast,
        mainLast: m.mainLast ?? (m.cupsMain ?? []).filter((c) => c.last).length,
        secLast: m.secLast ?? (m.cupsSec ?? []).filter((c) => c.last).length,
        hmLast: m.hmLast ?? (m.masters ?? []).filter((c) => c.last).length,
        snLast: m.snLast ?? (m.seasonal ?? []).filter((c) => c.last).length,
        wcLast: m.wcLast ?? (m.worldCup ?? []).filter((c) => c.last).length,
      };
    });
}

export async function getCabinet(userId: number): Promise<TrophyCabinet> {
  const { managers, leagues } = await load();
  const m = managers.find((x) => x.userId === userId);
  // Mirror getManagers' league fallback so an expanded cabinet stays consistent with the chart
  // under "Reigning only" even before a re-bake (cups need the bake — no `last`, no fallback).
  const latestByCountry = latestLeagueSeasonByCountry(leagues);
  const champ = (m?.titles ?? []).map((t) => ({
    main: `${t.country} champions`,
    sub: t.club,
    teamId: t.teamId,
    season: 'S' + t.season,
    last: t.last ?? latestByCountry.get(t.country) === t.season,
    flag: leagueFlagUrl(t.leagueId),
  }));
  const cupItems = (cups?: RawCup[]) =>
    (cups ?? []).map((t) => ({ main: t.cup, sub: t.club, teamId: t.teamId, season: 'S' + t.season, last: t.last, flag: leagueFlagUrl(t.leagueId) }));
  // `other` carries the Hattrick Masters, `seasonal` the Seasonal Cups, `worldCup` the World Cup
  // (senior + youth) — each its own category (see bake.ts / sync/masters.ts / sync/seasonal.ts /
  // sync/worldCup.ts). All three are country-less, so no flag.
  // National-team rows flag by id first, name second — see flags.ts nationFlagUrl for why.
  const nationFlag = nationFlagUrl;
  const nationalItems = (cups?: RawCup[]) =>
    (cups ?? []).map((t) => ({ main: t.cup, sub: t.club, teamId: t.teamId, season: 'S' + t.season, last: t.last, flag: nationFlag(t.club, t.leagueId) }));
  const medalItems = (place: number) =>
    (m?.medals ?? [])
      .filter((x) => x.place === place)
      .map((x) => ({ main: x.cup, sub: x.nation, season: 'S' + x.season, flag: nationFlag(x.nation, x.leagueId) }));
  return {
    champ, main: cupItems(m?.cupsMain), sec: cupItems(m?.cupsSec),
    other: cupItems(m?.masters), seasonal: cupItems(m?.seasonal), worldCup: nationalItems(m?.worldCup),
    silver: medalItems(2), bronze: medalItems(3),
  };
}

export async function getWinners(leagueId: string): Promise<Winner[]> {
  const { leagues, managers } = await load();
  const l = leagues.find((x) => String(x.leagueId) === leagueId);
  if (!l) return [];
  const natByLogin = new Map(managers.map((m) => [m.userName, m.nationality]));
  return l.champions.map((c) => ({ ...c, nationality: natByLogin.get(c.manager) }));
}

/**
 * World Cup (senior + youth) — the champion is a NATION, not a manager/club, so it's a completely
 * separate shape from Winner. No CHPP path exists for national-team competitions (cupmatches
 * returns nothing); the full roll of honour was scraped once from World/WorldCup/History.aspx
 * (see server/sync/worldCup.ts). The youth bracket was "U20" through edition 31, "U21" after.
 */
export interface WorldCupEdition {
  edition: number;
  ageGroup?: string;
  host: string;
  finished: string | null; // "DD.MM.YYYY", null while ongoing
  champion: string | null; // nation name, null while ongoing
  runnerUp: string | null;
  thirdFourth: string[];
  /** Set for the regional cups (scraped from Cup.aspx podium links); absent for World Cup editions,
   *  whose History.aspx source carries names only. Flags fall back to the name there. */
  championLeagueId?: number;
  runnerUpLeagueId?: number;
  thirdFourthLeagueIds?: number[];
  /** The manager coaching the champion nation when the edition finished (cross-referenced from
   *  NTFormerCoaches.aspx — see sync/worldCup.ts). Undefined when unattributed: "Retired user"
   *  tenure, no tenure recorded that far back, or the nation's team id never resolved. */
  coachUserId?: number;
  coach?: string;
  coachNationality?: string;
}
/**
 * A regional national-team cup — Africa / America / Asia and Oceania / Europe / Nations Cup (see
 * server/sync/ntCups.ts). Same nature as the World Cup, but perpetual: a champion per SEASON rather
 * than a numbered edition, which is the only reason it isn't just more WorldCupEditions.
 */
export interface RegionalCupSeason {
  season: number;
  host: string;
  finished: string | null; // "DD-MM-YYYY HH:MM" as printed, null while the season is running
  status?: string;
  champion: string | null;
  runnerUp: string | null;
  thirdFourth: string[];
  /** Podium league ids, index-aligned with `thirdFourth` — the reliable flag key (see flags.ts). */
  championLeagueId?: number;
  runnerUpLeagueId?: number;
  thirdFourthLeagueIds?: number[];
  coachUserId?: number;
  coach?: string;
  coachNationality?: string;
}
export interface RegionalCupRoll {
  cupId: number;
  cupName: string;
  isYouth: boolean;
  seasons: RegionalCupSeason[];
}
export interface WorldCupHistory {
  senior: WorldCupEdition[];
  youth: WorldCupEdition[];
  /** Absent in bakes that predate the regional cups — treated as an empty list. */
  regional?: RegionalCupRoll[];
}

const EMPTY_WC: WorldCupHistory = { senior: [], youth: [], regional: [] };

let worldCupBundle: Promise<WorldCupHistory> | null = null;
export async function getWorldCup(): Promise<WorldCupHistory> {
  if (!worldCupBundle) {
    worldCupBundle = fetch('/data/worldcup.json')
      .then((r) => (r.ok ? (r.json() as Promise<WorldCupHistory>) : EMPTY_WC))
      .catch(() => EMPTY_WC);
  }
  return worldCupBundle;
}

/**
 * Every national-team competition as one uniform list for the National trophies view: the World
 * Cup brackets keyed by edition, each regional cup keyed by season. Regional seasons are mapped
 * onto the same row shape (`edition` carries the season number) so one table renders them all —
 * `unitLabel` is what tells the reader which number they're looking at.
 */
export interface NationalCompetition {
  key: string;
  /** Cup names as they appear in a manager's baked record — the join key for per-coach medals.
   *  Usually one, and NOT always the display label (the youth World Cup bakes as "World Cup (Youth)"). */
  matchCups: string[];
  /** Full name, e.g. "U21 Europe Cup" — always shown on the roll of honour itself. */
  label: string;
  /** Bracket-independent name, e.g. "Europe Cup". Lets the senior and U21 lists read as the same
   *  set of competitions, and lets a bracket switch stay on the competition you were looking at. */
  shortLabel: string;
  isYouth: boolean;
  unitLabel: string;
  rows: WorldCupEdition[];
}

export async function getNationalCompetitions(): Promise<NationalCompetition[]> {
  const wc = await getWorldCup();
  const comps: NationalCompetition[] = [
    { key: 'senior', matchCups: ['World Cup'], label: 'World Cup', shortLabel: 'World Cup', isYouth: false, unitLabel: 'Ed.', rows: wc.senior },
    { key: 'youth', matchCups: ['World Cup (Youth)'], label: 'World Cup (Youth U20/U21)', shortLabel: 'World Cup', isYouth: true, unitLabel: 'Ed.', rows: wc.youth },
  ];
  for (const cup of wc.regional ?? []) {
    comps.push({
      key: `cup-${cup.cupId}`,
      matchCups: [cup.cupName],
      label: cup.cupName,
      shortLabel: cup.cupName.replace(/^U21\s+/, ''),
      isYouth: cup.isYouth,
      unitLabel: 'Season',
      rows: cup.seasons.map((s) => ({
        edition: s.season,
        host: s.host,
        finished: s.finished,
        champion: s.champion,
        runnerUp: s.runnerUp,
        thirdFourth: s.thirdFourth,
        championLeagueId: s.championLeagueId,
        runnerUpLeagueId: s.runnerUpLeagueId,
        thirdFourthLeagueIds: s.thirdFourthLeagueIds,
        coachUserId: s.coachUserId,
        coach: s.coach,
        coachNationality: s.coachNationality,
      })),
    });
  }
  return comps.filter((c) => c.rows.length > 0);
}

/** A coach's podium record in national-team competitions. */
export interface CoachMedals {
  userId: number;
  name: string;
  nationality?: string;
  g: number;
  s: number;
  b: number;
}

/**
 * Medal table by COACH, for the given competitions (matched on the cup names a manager's record
 * carries). Built from managers.json rather than worldcup.json: the rolls of honour name the
 * champion's coach only, while a manager's own record holds every podium place they took.
 *
 * World Cup editions therefore show golds but no medals — their History.aspx source never carried
 * a runner-up coach, unlike the regional cups scraped from the podium.
 */
export async function getCoachMedals(matchCups: string[]): Promise<CoachMedals[]> {
  const { managers } = await load();
  const want = new Set(matchCups);
  const out: CoachMedals[] = [];
  for (const m of managers) {
    const g = (m.worldCup ?? []).filter((t) => want.has(t.cup)).length;
    const medals = (m.medals ?? []).filter((x) => want.has(x.cup));
    const s = medals.filter((x) => x.place === 2).length;
    const b = medals.filter((x) => x.place === 3).length;
    if (g + s + b > 0) out.push({ userId: m.userId, name: m.userName, nationality: m.nationality, g, s, b });
  }
  return out.sort((a, b2) => b2.g - a.g || b2.s - a.s || b2.b - a.b || a.name.localeCompare(b2.name));
}

/**
 * National Coach elections — who a country's community voted to lead their national team for a
 * given World Cup cycle, independent of whether that country ever won anything. No CHPP path
 * exists; scraped once per country from World/Elections/History.aspx (see server/sync/elections.ts).
 * A country can list the SAME edition twice (a mid-cycle re-election) — that's intentional, not a
 * duplicate to collapse.
 */
export interface ElectionResult {
  leagueId: number;
  countryName: string;
  edition: number;
  host: string;
  winnerUserId?: number;
  winner?: string; // undefined = "A former user" (unattributed sentinel)
  winnerNationality?: string;
  votes?: string; // raw "37 (44%)" text
}

let electionsBundle: Promise<ElectionResult[]> | null = null;
function loadElections() {
  if (!electionsBundle) {
    electionsBundle = fetch('/data/elections.json')
      .then((r) => (r.ok ? (r.json() as Promise<ElectionResult[]>) : []))
      .catch(() => []);
  }
  return electionsBundle;
}

export async function getElectionCountries(): Promise<Country[]> {
  const rows = await loadElections();
  const seen = new Map<number, string>();
  for (const r of rows) if (!seen.has(r.leagueId)) seen.set(r.leagueId, r.countryName);
  return [...seen.entries()].map(([code, name]) => ({ code: String(code), name })).sort((a, b) => a.name.localeCompare(b.name));
}

export async function getElections(leagueId: string): Promise<ElectionResult[]> {
  const rows = await loadElections();
  return rows.filter((r) => String(r.leagueId) === leagueId).sort((a, b) => b.edition - a.edition);
}

/** Every election result, for the global "most elected" leaderboard (not scoped to one country). */
export async function getAllElections(): Promise<ElectionResult[]> {
  return loadElections();
}
